/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.voucherDAO;
import entity.voucher;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyen
 */
public class quanlyVoucher extends javax.swing.JPanel {

    voucherDAO vDao = new voucherDAO();

    /**
     * Creates new form quanLyVoucher
     */
    public quanlyVoucher() {
        initComponents();
        fillTable();
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblThongTin.getModel();
        model.setRowCount(0);
        List<voucher> voucherList = vDao.getAll();
        for (voucher vd : voucherList) {
            Object[] row = {vd.getMavoucher(), vd.getPhanTramGiam(), vd.getNgaybatdau(), vd.getNgayketthuc(), vd.isTrangthai()};
            model.addRow(row);
        }
        tblThongTin.setModel(model);
    }

    private voucher getData() {
        String mavoucher = txtMaVoucher.getText();
        int phantramgiam = Integer.valueOf(txtPhanTramGiam.getText());
        String ngaybatdau = txtNgayBatDau.getText();
        String ngayketthuc = txtNgayKetThuc.getText();
        boolean trangthai = jrCon.isSelected();
        return new voucher(mavoucher, phantramgiam, ngaybatdau, ngayketthuc, trangthai);
    }

    private void fillFirstRowTable() {
        if (tblThongTin.getRowCount() > 0) {
            txtMaVoucher.setText(String.valueOf(tblThongTin.getValueAt(0, 0)));
            txtPhanTramGiam.setText(String.valueOf(tblThongTin.getValueAt(0, 1)));
            Object ngayBatDauObj = tblThongTin.getValueAt(0, 2);
            int ngayBatDau = ngayBatDauObj instanceof Number ? ((Number) ngayBatDauObj).intValue() : Integer.parseInt(ngayBatDauObj.toString());
            txtNgayBatDau.setText(String.valueOf(ngayBatDau));

            Object ngayKetThucObj = tblThongTin.getValueAt(0, 3);
            int ngayKetThuc = ngayKetThucObj instanceof Number ? ((Number) ngayKetThucObj).intValue() : Integer.parseInt(ngayKetThucObj.toString());
            txtNgayKetThuc.setText(String.valueOf(ngayKetThuc));

            // Lấy giá trị boolean từ cột thứ tư và thiết lập radio button tương ứng
            boolean trangthai = (boolean) tblThongTin.getValueAt(0, 4);
            if (trangthai) {
                jrCon.setSelected(true);
                jrHet.setSelected(false);
            } else {
                jrCon.setSelected(false);
                jrHet.setSelected(true);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTin = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMaVoucher = new javax.swing.JTextField();
        txtNgayKetThuc = new javax.swing.JTextField();
        jrCon = new javax.swing.JRadioButton();
        jrHet = new javax.swing.JRadioButton();
        txtNgayBatDau = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPhanTramGiam = new javax.swing.JTextField();

        jLabel3.setText("QUẢN LÝ VOUCHER");

        tblThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Voucher", "Phần trăm giảm", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Trạng Thái"
            }
        ));
        tblThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongTin);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText("Tìm kiếm");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jButton5.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField6))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton5)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("danh sách", jPanel1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Phần trăm giảm");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Ngày Kết Thúc");

        btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnXoa.setText("xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSua.setText("sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Trạng Thái");

        jrCon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jrCon.setText("Còn");

        jrHet.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jrHet.setText("Hết");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Ngày Bắt Đầu");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Mã Voucher");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(btnSua)
                        .addGap(128, 128, 128)
                        .addComponent(btnXoa))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayBatDau, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayKetThuc)
                            .addComponent(txtMaVoucher, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPhanTramGiam))))
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(85, 85, 85)
                        .addComponent(jrCon)
                        .addGap(53, 53, 53)
                        .addComponent(jrHet)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jrCon)
                    .addComponent(jrHet))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(361, 361, 361))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("cập nhật ", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Bạn muốn thêm dữ liệu?", "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            try {
                // Khởi tạo đối tượng voucherDAO
                voucherDAO vDao = new voucherDAO();

                // Lấy dữ liệu từ giao diện người dùng
                voucher newVoucher = this.getData();

                // Thêm dữ liệu vào cơ sở dữ liệu
                boolean isAdded = vDao.add(newVoucher);

                if (isAdded) {
                    // Cập nhật giao diện bảng
                    this.fillTable();

                    // Thông báo thành công
                    JOptionPane.showMessageDialog(this, "Thêm dữ liệu thành công!");
                } else {
                    // Thông báo lỗi nếu không thêm được dữ liệu
                    JOptionPane.showMessageDialog(this, "Thêm dữ liệu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                // Thông báo lỗi nếu có ngoại lệ
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here: 
        int row = tblThongTin.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để sửa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Xác nhận hành động sửa
        int result = JOptionPane.showConfirmDialog(this, "Bạn muốn sửa dữ liệu?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            try {
                // Lấy dữ liệu từ giao diện người dùng
                String maVC = txtMaVoucher.getText();
                int phantramgiam = Integer.valueOf(txtMaVoucher.getText());
                String ngayBatDau = txtNgayBatDau.getText();
                String ngayKetThuc = txtNgayKetThuc.getText();
                boolean trangThai = jrCon.isSelected();

                // Tạo đối tượng voucher mới
                voucher updatedVoucher = new voucher(maVC, phantramgiam, ngayBatDau, ngayKetThuc, trangThai);

                // Cập nhật dữ liệu vào cơ sở dữ liệu
                boolean isUpdated = vDao.update(updatedVoucher);

                if (isUpdated) {
                    // Cập nhật giao diện bảng
                    this.fillTable();

                    // Xóa dữ liệu trong các trường nhập liệu
                    txtMaVoucher.setText("");
                    txtNgayBatDau.setText("");
                    txtNgayKetThuc.setText("");
                    jrCon.setSelected(true); // Hoặc jrhet tùy thuộc vào trạng thái mặc định

                    // Thông báo thành công
                    JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thành công!");
                } else {
                    // Thông báo lỗi nếu không cập nhật được dữ liệu
                    JOptionPane.showMessageDialog(this, "Cập nhật dữ liệu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                // Thông báo lỗi định dạng số
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số hợp lệ cho Ngày Bắt Đầu và Ngày Kết Thúc.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                // Thông báo lỗi nếu có ngoại lệ SQL
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int rowIndex = tblThongTin.getSelectedRow();
        if (rowIndex >= 0) {
            // Confirm the deletion
            int result = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa dữ liệu?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                String maVoucher = (String) tblThongTin.getValueAt(rowIndex, 0);
                try {
                    // Initialize voucherDAO
                    voucherDAO vDao = new voucherDAO();

                    // Perform the deletion
                    boolean isDeleted = vDao.delete(maVoucher);

                    if (isDeleted) {
                        // Refresh the table
                        this.fillTable();
                        // Clear form fields
                        txtMaVoucher.setText("");
                        txtNgayBatDau.setText("");
                        txtNgayKetThuc.setText("");
                        jrCon.setSelected(true); // Or jrHet, based on your default

                        // Show success message
                        JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công!");
                    } else {
                        // Show failure message
                        JOptionPane.showMessageDialog(this, "Xóa dữ liệu thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    // Show error message
                    JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        } else {
            // Inform user to select a row
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng để xóa.", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinMouseClicked
        int rowIndex = tblThongTin.getSelectedRow();
        if (rowIndex >= 0) {
            // Get data from the selected row
            String maVoucher = (String) tblThongTin.getValueAt(rowIndex, 0);
            String phamTram = (String) tblThongTin.getValueAt(rowIndex, 1);
            String ngayBatDau = (String) tblThongTin.getValueAt(rowIndex, 2);
            String ngayKetThuc = (String) tblThongTin.getValueAt(rowIndex, 3);
            boolean trangThai = (boolean) tblThongTin.getValueAt(rowIndex, 4);

            // Set data to form fields
            txtMaVoucher.setText(maVoucher);
            txtPhanTramGiam.setText(phamTram);
            txtNgayBatDau.setText(ngayBatDau);
            txtNgayKetThuc.setText(ngayKetThuc);
            if (trangThai) {
                jrCon.setSelected(true);
                jrHet.setSelected(false);
            } else {
                jrCon.setSelected(false);
                jrHet.setSelected(true);
            }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_tblThongTinMouseClicked

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblThongTin.getModel();
        
        String timKiem = jTextField6.getText().trim();
        
        List<voucher> vcList = new voucherDAO().findByIDVoucher(timKiem);
        
        model = (DefaultTableModel) tblThongTin.getModel();
        model.setRowCount(0);

        for (voucher vd : vcList) {
            Object[] row = {vd.getMavoucher(), vd.getPhanTramGiam(), vd.getNgaybatdau(), vd.getNgayketthuc(), vd.isTrangthai()};
            model.addRow(row);
        }


    }//GEN-LAST:event_jTextField6KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JRadioButton jrCon;
    private javax.swing.JRadioButton jrHet;
    private javax.swing.JTable tblThongTin;
    private javax.swing.JTextField txtMaVoucher;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtPhanTramGiam;
    // End of variables declaration//GEN-END:variables
}
