/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.chiTietHoaDonDAO;
import DAO.chitietsanphamDAO;
import DAO.danhMucDAO;
import DAO.hoaDonDAO;
import DAO.khachHangDao;
import DAO.mauSacDAO;
import DAO.nhanhVienDAO;
import DAO.sanPhamDAO;
import DAO.sizeDAO;
import DAO.thuongHieuDAO;
import DAO.voucherDAO;
import Helper.Auth;
import Helper.Ivoice;
import Helper.MsgBox;
import Helper.VoucherSupport;
import View.viewModel.ProductDetail;
import entity.chitiethoadon;
import entity.chitietsanpham;
import entity.danhmuc;
import entity.hoadon;
import entity.khachHang;
import entity.mausac;
import entity.sanpham;
import entity.size;
import entity.thuonghieu;
import entity.voucher;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyen
 */
public class quanLyBanHang extends javax.swing.JPanel {

    LocalDate currentDate = LocalDate.now();
    LocalDateTime dateNow = LocalDateTime.now();
    private voucherDAO vcDao;
    private khachHangDao khDao;
    private sizeDAO sizeDao;
    private mauSacDAO msDao;
    private danhMucDAO dmDao;
    private thuongHieuDAO thDao;
    private sanPhamDAO spDAO;
    private hoaDonDAO hdDAO;
    private nhanhVienDAO nvDAO;
    private chiTietHoaDonDAO cthdDAO;
    private chitietsanphamDAO ctspDao;
    DefaultTableModel model;
    Trangchu mainFrame;

    /**
     * Creates new form quanLyBanHang
     */
    public quanLyBanHang() {
        initComponents();
        this.mainFrame = new Trangchu();
        ctspDao = new chitietsanphamDAO();
        vcDao = new voucherDAO();
        khDao = new khachHangDao();
        msDao = new mauSacDAO();
        hdDAO = new hoaDonDAO();
        dmDao = new danhMucDAO();
        thDao = new thuongHieuDAO();
        sizeDao = new sizeDAO();
        cthdDAO = new chiTietHoaDonDAO();
        ngayTaoHD();
        fill();
        fillCbbSize();
        fillCbbTH();
        fillCbbDM();
        fillCbbColor();
        fillDataTableSanPham();
//        this.setExtendedState(MAXIMIZED_BOTH);
    }

    void fill() {
        List<hoadon> lhd = hdDAO.getAll();
        fillDataTableHoaDon(lhd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Ao = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblMa_HD = new javax.swing.JLabel();
        txtMa_HD = new javax.swing.JTextField();
        lblNgayLap = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taeGhiChu_HD = new javax.swing.JTextArea();
        lblGhiChu_HD = new javax.swing.JLabel();
        lblTongTien_HD = new javax.swing.JLabel();
        txtTongTien_HD = new javax.swing.JTextField();
        lblTrangThai_HD = new javax.swing.JLabel();
        jrDonCho = new javax.swing.JRadioButton();
        jrDaThanhToan = new javax.swing.JRadioButton();
        btnTao_HD = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnSua_HD = new javax.swing.JButton();
        lblVoucher = new javax.swing.JLabel();
        txtVoucher = new javax.swing.JTextField();
        lblTbVoucher = new javax.swing.JLabel();
        lblTT_thanhtoan = new javax.swing.JLabel();
        lblTongTien_HD1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        btnXuatHD = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        lblNgayLap1 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        lblNgayLap2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTSP = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblHoaDon_HoaDon = new javax.swing.JTable();
        txtFindProduct = new javax.swing.JTextField();
        lblSoLuong_CTPM2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblCTHoaDon_ChiTietHoaDon = new javax.swing.JTable();
        lblSoLuong_CTPM4 = new javax.swing.JLabel();
        txtIIDCTHD = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSoLuong_ChiTietHoaDon = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cbbSize = new javax.swing.JComboBox<>();
        cbbTH = new javax.swing.JComboBox<>();
        cbbDanhMuc = new javax.swing.JComboBox<>();
        lblSoLuong_CTPM5 = new javax.swing.JLabel();
        lblSoLuong_CTPM6 = new javax.swing.JLabel();
        lblSoLuong_CTPM7 = new javax.swing.JLabel();
        cbbColor = new javax.swing.JComboBox<>();
        lblSoLuong_CTPM8 = new javax.swing.JLabel();
        txtRowHD = new javax.swing.JLabel();

        Ao.setText("jLabel1");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMa_HD.setText("Mã Hoá Đơn");

        txtMa_HD.setEditable(false);

        lblNgayLap.setText("Ngày lập");

        txtNgayLap.setEditable(false);

        taeGhiChu_HD.setColumns(20);
        taeGhiChu_HD.setRows(5);
        jScrollPane3.setViewportView(taeGhiChu_HD);

        lblGhiChu_HD.setText("Ghi chú");

        lblTongTien_HD.setText("Tổng tiền");

        txtTongTien_HD.setEditable(false);
        txtTongTien_HD.setText("0");

        lblTrangThai_HD.setText("Trạng thái");

        buttonGroup1.add(jrDonCho);
        jrDonCho.setText("Đơn chờ");
        jrDonCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDonChoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrDaThanhToan);
        jrDaThanhToan.setText("Đã thanh toán");
        jrDaThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDaThanhToanActionPerformed(evt);
            }
        });

        btnTao_HD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTao_HD.setText("Tạo hoá đơn");
        btnTao_HD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTao_HDActionPerformed(evt);
            }
        });

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnSua_HD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua_HD.setText("Sửa");
        btnSua_HD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_HDActionPerformed(evt);
            }
        });

        lblVoucher.setText("Voucher ");

        txtVoucher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVoucherKeyReleased(evt);
            }
        });

        lblTbVoucher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTbVoucher.setText("Voucher ");

        lblTT_thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTT_thanhtoan.setText("0");

        lblTongTien_HD1.setText("Cần thanh toán");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnReset1.setText("Hoá đơn đã thanh toán");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        btnXuatHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXuatHD.setText("Huỷ hoá đơn");
        btnXuatHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHDActionPerformed(evt);
            }
        });

        btnReset2.setText("Hoá đơn huỷ");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        lblNgayLap1.setText("SDT");

        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSDTKeyReleased(evt);
            }
        });

        lblNgayLap2.setText("Tên KH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXuatHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTao_HD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMa_HD)
                                .addGap(18, 18, 18)
                                .addComponent(txtMa_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSua_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrangThai_HD)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGhiChu_HD)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTbVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblVoucher)
                        .addGap(43, 43, 43)
                        .addComponent(txtVoucher)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrDonCho, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTongTien_HD1)
                                .addGap(9, 9, 9)
                                .addComponent(lblTT_thanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTongTien_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNgayLap)
                            .addComponent(lblNgayLap1)
                            .addComponent(lblNgayLap2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtTongTien_HD, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(txtTenKH))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnReset1)
                    .addComponent(btnReset2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMa_HD)
                    .addComponent(txtMa_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayLap1)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNgayLap2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayLap)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien_HD)
                    .addComponent(txtTongTien_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien_HD1)
                    .addComponent(lblTT_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVoucher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTbVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrangThai_HD)
                            .addComponent(jrDonCho))
                        .addGap(7, 7, 7)
                        .addComponent(jrDaThanhToan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTao_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGhiChu_HD))
                .addGap(43, 43, 43))
        );

        jTabbedPane1.addTab("Hoá đơn", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(1065, 498));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản phẩm"));

        tblCTSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên sản phẩm", "Số lượng", "Đơn Giá", "Danh mục", "Thương hiệu", "Kích cỡ", "Màu", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCTSP.setRowHeight(30);
        tblCTSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTSPMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblCTSPMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblCTSP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Hoá đơn"));

        tblHoaDon_HoaDon.setAutoCreateRowSorter(true);
        tblHoaDon_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Nhân Viên", "SDT", "Tên KH", "Voucher ", "Ngày lập hoá đơn", "Tổng tiền", "TT Thanh toan", "Ghi chú", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblHoaDon_HoaDon.setPreferredSize(new java.awt.Dimension(825, 220));
        tblHoaDon_HoaDon.setRowHeight(30);
        tblHoaDon_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMouseReleased(evt);
            }
        });
        jScrollPane10.setViewportView(tblHoaDon_HoaDon);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );

        txtFindProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindProductActionPerformed(evt);
            }
        });
        txtFindProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindProductKeyReleased(evt);
            }
        });

        lblSoLuong_CTPM2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM2.setText("Tìm Kiếm");
        lblSoLuong_CTPM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM2MouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi Tiết Hoá Đơn"));

        tblCTHoaDon_ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Giá", "Trạng thái"
            }
        ));
        tblCTHoaDon_ChiTietHoaDon.setRowHeight(30);
        tblCTHoaDon_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTHoaDon_ChiTietHoaDonMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblCTHoaDon_ChiTietHoaDonMouseReleased(evt);
            }
        });
        jScrollPane15.setViewportView(tblCTHoaDon_ChiTietHoaDon);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        lblSoLuong_CTPM4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM4.setText("ID");
        lblSoLuong_CTPM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM4MouseClicked(evt);
            }
        });

        jLabel14.setText("Số lượng");

        txtSoLuong_ChiTietHoaDon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtSoLuong_ChiTietHoaDonStateChanged(evt);
            }
        });
        txtSoLuong_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoLuong_ChiTietHoaDonMouseClicked(evt);
            }
        });
        txtSoLuong_ChiTietHoaDon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSoLuong_ChiTietHoaDonPropertyChange(evt);
            }
        });

        jButton4.setText("Thay đổi số lượng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Xoá");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cbbSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSizeActionPerformed(evt);
            }
        });

        cbbTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTHActionPerformed(evt);
            }
        });

        cbbDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDanhMucActionPerformed(evt);
            }
        });

        lblSoLuong_CTPM5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM5.setText("Size");
        lblSoLuong_CTPM5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM5MouseClicked(evt);
            }
        });

        lblSoLuong_CTPM6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM6.setText("Thương hiệu");
        lblSoLuong_CTPM6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM6MouseClicked(evt);
            }
        });

        lblSoLuong_CTPM7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM7.setText("Danh mục");
        lblSoLuong_CTPM7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM7MouseClicked(evt);
            }
        });

        cbbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL" }));
        cbbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbColorActionPerformed(evt);
            }
        });

        lblSoLuong_CTPM8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM8.setText("Màu");
        lblSoLuong_CTPM8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM8MouseClicked(evt);
            }
        });

        txtRowHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRowHD.setText("HD: ");
        txtRowHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRowHDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSoLuong_CTPM2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSoLuong_CTPM8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoLuong_CTPM5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoLuong_CTPM6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbbTH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSoLuong_CTPM7, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtRowHD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSoLuong_CTPM4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIIDCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(209, 209, 209)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtSoLuong_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(38, 38, 38)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSoLuong_CTPM8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSoLuong_CTPM2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong_CTPM5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong_CTPM6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong_CTPM7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtSoLuong_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIIDCTHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong_CTPM4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(txtRowHD, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 908, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 378, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCTSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseClicked

    }//GEN-LAST:event_tblCTSPMouseClicked
    int idSP = 0;
    int maHD = 0;
    double giaSP = 0;
    private void tblCTSPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseReleased
        int row = tblCTSP.getSelectedRow();

        // Lấy số lượng sản phẩm từ bảng
        int slSP = Integer.parseInt(tblCTSP.getValueAt(row, 2).toString());

        // Kiểm tra nếu chưa chọn hóa đơn
        if (txtMa_HD.getText().isEmpty()) {
            MsgBox.alert(jPanel1, "Chưa chọn hoá đơn");
            return; // Thoát nếu chưa chọn hóa đơn
        }

        // Lấy ID hóa đơn và thông tin sản phẩm từ bảng
        int idHD = Integer.parseInt(txtMa_HD.getText());
        int idSP = Integer.parseInt(tblCTSP.getValueAt(row, 0).toString());
        double giaSP = Double.parseDouble(tblCTSP.getValueAt(row, 3).toString());

        // Lấy thông tin chi tiết sản phẩm từ cơ sở dữ liệu
        ProductDetail prd = hdDAO.fillSLvsGiaProduct(idSP);

        // Lấy danh sách chi tiết hóa đơn cho sản phẩm và hóa đơn hiện tại
        List<chitiethoadon> lstCTHD = cthdDAO.selectSLByIDCTSP(idHD, idSP);

        // Nếu sản phẩm chưa có trong hóa đơn
        if (prd != null) {
            if (lstCTHD.isEmpty()) {
                // Thêm sản phẩm mới vào hóa đơn
                chitiethoadon op = new chitiethoadon();
                op.setIdhd(idHD);
                op.setIdctsp(idSP);
                op.setTenSP(prd.getProductName());
                op.setSoluong(1);
                op.setDon_gia(prd.getPrice());
                op.setGia(prd.getPrice());
                cthdDAO.add(op);

                // Cập nhật bảng chi tiết hóa đơn và số lượng sản phẩm trong kho
                fillDataTableChiTietHoaDon(idHD);
                // cập nhật số lượng sản phẩm trong kho
                if (slSP <= 0) {
                    MsgBox.alert(this, "Số lượng sản phẩm ít hơn 0");

                } else {
                    int slSPs = slSP - 1;
                    ctspDao.updateSL(slSPs, idSP);
                    System.out.println("SLSPs: " + slSPs);
                }
                // Cập nhật tổng tiền hóa đơn
                List<hoadon> lstHDByTongtien = hdDAO.getHDByID(idHD);
                for (hoadon hoadons : lstHDByTongtien) {
                    txtTongTien_HD.setText(String.valueOf(hoadons.getTongtien()));
                }

                // Tìm kiếm voucher và cập nhật giao diện
                searchVoucher();
            } else {
                // Cập nhật số lượng sản phẩm nếu đã có trong hóa đơn
                chitiethoadon ctV2 = lstCTHD.get(0);
                int tangSL = ctV2.getSoluong() + 1;
                ctV2.setSoluong(tangSL);
                double gia = prd.getPrice();
                double tong_gia = gia * tangSL;
                ctV2.setGia(tong_gia);
                cthdDAO.updateSL(ctV2);

                // Cập nhật số lượng sản phẩm trong kho
                if (slSP <= 0) {
                    MsgBox.alert(this, "Số lượng sản phẩm ít hơn 0");

                } else {
                    int slSPs = slSP - 1;
                    ctspDao.updateSL(slSPs, idSP);
                    System.out.println("SLSPs: " + slSPs);
                }

                // Cập nhật tổng tiền hóa đơn
                List<hoadon> lstHDByTongtien = hdDAO.getHDByID(idHD);
                for (hoadon hoadons : lstHDByTongtien) {
                    txtTongTien_HD.setText(String.valueOf(hoadons.getTongtien()));
                }

                // Tìm kiếm voucher và cập nhật giao diện
                searchVoucher();
            }
        }

        // Cập nhật giao diện và bảng dữ liệu
        update();
        fillDataTableChiTietHoaDon(idHD);
        List<hoadon> lhd = hdDAO.getAll();
        fillDataTableHoaDon(lhd);
        fillDataTableSanPham();
    }//GEN-LAST:event_tblCTSPMouseReleased

    private void tblHoaDon_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMouseClicked
        //        System.out.println("clicked");
    }//GEN-LAST:event_tblHoaDon_HoaDonMouseClicked

    private void tblHoaDon_HoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDon_HoaDonMouseEntered

    private void tblHoaDon_HoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDon_HoaDonMousePressed

    private void tblHoaDon_HoaDonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMouseReleased
        int row = tblHoaDon_HoaDon.getSelectedRow();
        txtRowHD.setText(String.valueOf(row));
        txtMa_HD.setText(tblHoaDon_HoaDon.getValueAt(row, 0).toString());
        maHD = Integer.parseInt(tblHoaDon_HoaDon.getValueAt(row, 0).toString());
        Ao.setText(tblHoaDon_HoaDon.getValueAt(row, 1).toString());
        txtSDT.setText(tblHoaDon_HoaDon.getValueAt(row, 2).toString());
        txtTenKH.setText(tblHoaDon_HoaDon.getValueAt(row, 3).toString());
        txtVoucher.setText(tblHoaDon_HoaDon.getValueAt(row, 4).toString());
        txtNgayLap.setText(tblHoaDon_HoaDon.getValueAt(row, 5).toString());
        txtTongTien_HD.setText(tblHoaDon_HoaDon.getValueAt(row, 6).toString());
        lblTT_thanhtoan.setText(tblHoaDon_HoaDon.getValueAt(row, 7).toString());
        taeGhiChu_HD.setText(tblHoaDon_HoaDon.getValueAt(row, 8).toString());
        String trangThai = tblHoaDon_HoaDon.getValueAt(row, 9).toString();
        if (trangThai.equals("true")) {
            jrDonCho.setSelected(true);
        } else {
            jrDaThanhToan.setSelected(true);
        }

        int id = Integer.valueOf(txtMa_HD.getText());
        Ivoice.hd = hdDAO.findByID(id);
        searchVoucher();
        fillDataTableChiTietHoaDon(id);
    }//GEN-LAST:event_tblHoaDon_HoaDonMouseReleased

    private void txtFindProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindProductActionPerformed

    private void lblSoLuong_CTPM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM2MouseClicked

    private void tblCTHoaDon_ChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHoaDon_ChiTietHoaDonMouseClicked
        int row = tblCTHoaDon_ChiTietHoaDon.getSelectedRow();
        txtIIDCTHD.setText(tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 0).toString());
        txtSoLuong_ChiTietHoaDon.setValue(tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 3));
    }//GEN-LAST:event_tblCTHoaDon_ChiTietHoaDonMouseClicked

    private void tblCTHoaDon_ChiTietHoaDonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHoaDon_ChiTietHoaDonMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tblCTHoaDon_ChiTietHoaDonMouseReleased

    private void txtSoLuong_ChiTietHoaDonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtSoLuong_ChiTietHoaDonStateChanged

    }//GEN-LAST:event_txtSoLuong_ChiTietHoaDonStateChanged

    private void txtSoLuong_ChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoLuong_ChiTietHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuong_ChiTietHoaDonMouseClicked

    private void txtSoLuong_ChiTietHoaDonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSoLuong_ChiTietHoaDonPropertyChange

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuong_ChiTietHoaDonPropertyChange

    private void lblSoLuong_CTPM4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM4MouseClicked

    private void jrDonChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDonChoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrDonChoActionPerformed

    private void jrDaThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDaThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrDaThanhToanActionPerformed

    private void txtFindProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindProductKeyReleased
        // TODO add your handling code here:
//        System.out.println(jTextField9.getText());
        String name = txtFindProduct.getText();
        List<ProductDetail> lstprd = hdDAO.findByNameProduct(name);
        FillByFindProduct(lstprd);
    }//GEN-LAST:event_txtFindProductKeyReleased

    private void lblSoLuong_CTPM5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM5MouseClicked

    private void lblSoLuong_CTPM6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM6MouseClicked

    private void lblSoLuong_CTPM7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM7MouseClicked

    private void cbbDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDanhMucActionPerformed
        // TODO add your handling code here:
        findByCategory();
    }//GEN-LAST:event_cbbDanhMucActionPerformed

    private void lblSoLuong_CTPM8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM8MouseClicked

    private void cbbSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSizeActionPerformed
        // TODO add your handling code here:
        findBySize();
    }//GEN-LAST:event_cbbSizeActionPerformed

    private void cbbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbColorActionPerformed
        // TODO add your handling code here:
        if (cbbColor.getSelectedItem().equals("ALL")) {
            fillDataTableSanPham();
        } else {

            findByColor();
        }
    }//GEN-LAST:event_cbbColorActionPerformed

    private void cbbTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTHActionPerformed
        // TODO add your handling code here:
        findByBrand();
    }//GEN-LAST:event_cbbTHActionPerformed

    private void btnTao_HDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTao_HDActionPerformed
        // TODO add your handling code here:
        txtTongTien_HD.setText("0");
        hdDAO.add(getFormData());
        List<hoadon> lhd = hdDAO.getAll();
        fillDataTableHoaDon(lhd);
    }//GEN-LAST:event_btnTao_HDActionPerformed
    void searchVoucher() {
        voucher vouchers = vcDao.findByMaVoucher(txtVoucher.getText());
        if (txtVoucher.getText().trim().isEmpty()) {
            lblTbVoucher.setText("");
            btnTao_HD.setEnabled(true);
            return;
        }

        if (vouchers == null) {
            lblTbVoucher.setForeground(Color.red);
            lblTbVoucher.setText("voucher không tồn tại");
            System.out.println("voucher không tồn tại");
            btnTao_HD.setEnabled(false);
        } else {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String stopDate = vouchers.getNgayketthuc();
            LocalDate inputDate = LocalDate.parse(stopDate, formatter);
            if (currentDate.isAfter(inputDate)) {

                lblTbVoucher.setForeground(Color.red);
                lblTbVoucher.setText("voucher đã hết hạn");
                System.out.println(vouchers.getNgayketthuc());
                btnTao_HD.setEnabled(false);

            } else if (currentDate.isBefore(inputDate)) {

                lblTbVoucher.setForeground(Color.green);
                lblTbVoucher.setText("voucher có hiệu lực");
                System.out.println(vouchers.getNgayketthuc());
                btnTao_HD.setEnabled(true);

                int tongtien = Integer.valueOf(txtTongTien_HD.getText());
                int voucher = vouchers.getPhanTramGiam();
                System.out.println(voucher);

                double discount = (double) voucher / 100;
                int tt_thanhtoan = (int) (tongtien - (tongtien * discount));

                lblTT_thanhtoan.setText(String.valueOf(tt_thanhtoan));
                System.out.println(tt_thanhtoan);

                VoucherSupport.vch = vouchers;
            } else {

                lblTbVoucher.setForeground(Color.green);
                lblTbVoucher.setText("voucher có hiệu lực");
                System.out.println(vouchers.getNgayketthuc());
                btnTao_HD.setEnabled(true);

                int tongtien = Integer.valueOf(txtTongTien_HD.getText());
                int voucher = vouchers.getPhanTramGiam();
                System.out.println(voucher);

                double discount = (double) voucher / 100;
                int tt_thanhtoan = (int) (tongtien - (tongtien * discount));

                lblTT_thanhtoan.setText(String.valueOf(tt_thanhtoan));
                System.out.println(tt_thanhtoan);

                VoucherSupport.vch = vouchers;
            }
        }
    }
    private void txtVoucherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoucherKeyReleased
        // TODO add your handling code here:
        searchVoucher();
    }//GEN-LAST:event_txtVoucherKeyReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtFindProduct.setText("");
        txtMa_HD.setText("");
        lblTT_thanhtoan.setText("0");
        txtNgayLap.setText("");
        txtSoLuong_ChiTietHoaDon.setValue(0);
        txtTongTien_HD.setText("");
        txtVoucher.setText("");
        taeGhiChu_HD.setText("");
        tblCTSP.setVisible(true);
        tblCTSP.setEnabled(true);
        fill();
        ngayTaoHD();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        tblCTSP.setEnabled(false);
        tblCTSP.setVisible(false);
        fillDataTableHoaDon(hdDAO.getAllByDathanhtoan());
    }//GEN-LAST:event_btnReset1ActionPerformed
    void update() {
        int row = tblHoaDon_HoaDon.getSelectedRow();
        int modelRow = Integer.valueOf(txtRowHD.getText());

        int idhd = Integer.valueOf(txtMa_HD.getText());
        int idnv = Auth.user.getId();
        String sdt = txtSDT.getText();
        String TenKH = txtTenKH.getText();
        String mavoucher = txtVoucher.getText();
        String thoigian = txtNgayLap.getText();
        String ghichu = taeGhiChu_HD.getText();
        int ttthanhtoan = Integer.valueOf(lblTT_thanhtoan.getText());
        int tongtien = Integer.valueOf(txtTongTien_HD.getText());
        System.out.println("Line 1058: " + tongtien);

        hoadon hd = new hoadon(idhd, idnv, sdt, TenKH, mavoucher, thoigian, ghichu, ttthanhtoan, tongtien, 1);
        hdDAO.update(hd);
        fill();
    }

    private void btnSua_HDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_HDActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSua_HDActionPerformed

    private void btnXuatHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHDActionPerformed
        // TODO add your handling code here:
        hdDAO.huyHD(Integer.valueOf(txtMa_HD.getText()));
        fill();

    }//GEN-LAST:event_btnXuatHDActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        hdDAO.thanhtoan(Integer.valueOf(txtMa_HD.getText()));
        fill();

        int id_hd = Integer.valueOf(txtMa_HD.getText());
        XuatHDDialog hd = new XuatHDDialog(mainFrame, true, id_hd);
        hd.setVisible(true);
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
//        System.out.println("IDCTSP: " + idCtsp);
        if (MsgBox.confirm(jPanel1, "Bạn muốn xoá sản phẩm này khỏi hoá đơn?")) {
            
            int row = tblCTHoaDon_ChiTietHoaDon.getSelectedRow();
            String idStr = tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 0).toString();
            int id = Integer.valueOf(idStr);
            // tim kiem san pham
            int idSP = Integer.valueOf(tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 1).toString());
            chitietsanpham sp = ctspDao.findByID(idSP);
            // cap nhat so luong tra lai
            int sLHD = Integer.valueOf(tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 3).toString());
            int sLtralai = sLHD + sp.getSoLuong();
            ctspDao.updateSL(sLtralai, idSP);
            cthdDAO.delete(id);
            fillDataTableSanPham();
            fillDataTableChiTietHoaDon(Ivoice.hd.getId());
            fill();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtRowHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRowHDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRowHDMouseClicked

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        // TODO add your handling code here:
        tblCTSP.setVisible(false);
        fillDataTableHoaDon(hdDAO.getAllByDaHuy());
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void txtSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyReleased
        // TODO add your handling code here:

        try {
            String sdt = txtSDT.getText();
            khachHang kh = khDao.findKH(sdt);
            txtTenKH.setText(kh.getTenKhachHang());
        } catch (Exception e) {
            txtTenKH.setText("Không tồn tại");

        }
    }//GEN-LAST:event_txtSDTKeyReleased
    int idCthd = 0;

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        updateChiTietHoaDon();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void updateChiTietHoaDon() {
        // Lấy số lượng sản phẩm mới từ giao diện
        int slSPText = Integer.valueOf(txtSoLuong_ChiTietHoaDon.getValue().toString());

        // Lấy chỉ số hàng được chọn trong bảng chi tiết hóa đơn
        int row = tblCTHoaDon_ChiTietHoaDon.getSelectedRow();

        // Lấy ID sản phẩm từ hàng được chọn
        int idCtsp = Integer.parseInt(tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 1).toString());
        chitietsanpham ctsp = ctspDao.findByID(idCtsp);

        // Lấy số lượng sản phẩm hiện có trong kho
        int slSP = ctsp.getSoLuong();

        // Lấy mã chi tiết hóa đơn từ hàng được chọn
        String idStr = tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 0).toString();
        int idCthd = Integer.valueOf(idStr);

        // Lấy mã hóa đơn
        int idHD = Integer.parseInt(txtMa_HD.getText());

        // Lấy giá sản phẩm và số lượng mới từ giao diện
        double giaSP = Double.parseDouble(tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 4).toString());
        int newSL = Integer.parseInt(txtSoLuong_ChiTietHoaDon.getValue().toString());

        // Tạo đối tượng chitiethoadon để cập nhật
        chitiethoadon cthd = new chitiethoadon();
        cthd.setSoluong(newSL);

        int slCTHD = Integer.valueOf(tblCTHoaDon_ChiTietHoaDon.getValueAt(row, 3).toString());
        int slthua = slCTHD - slSPText;
        // Kiểm tra và cập nhật số lượng sản phẩm
        if (slSP < 0) {
            // Nếu số lượng sản phẩm hiện có là 0 hoặc ít hơn
            MsgBox.alert(this, "Số lượng sản phẩm ít hơn 0");
        } else if (slSP == 0) {
            if (MsgBox.confirm(this, "Bạn đồng ý trả lại " + slthua + " món hàng?")) {
                ctspDao.updateSL(slthua, idCtsp);
                fillDataTableSanPham();
            }
        } else {
            // Nếu số lượng mới không vượt quá số lượng hiện có
            if (slSPText <= slSP) {
                // Lấy số lượng sản phẩm hiện tại trong chi tiết hóa đơn

                // Cập nhật số lượng sản phẩm trong kho
                if (slthua > 0) {
                    int slSPs = slSP + slthua;
                    ctspDao.updateSL(slSPs, idCtsp);
                } else {
                    System.out.println("SLThua" + slthua);
                    int sltralai = slSP - Math.abs(slthua);
                    ctspDao.updateSL(sltralai, idCtsp);
                }

                // Tính tổng giá dựa trên đơn giá và số lượng mới
                double tong_gia = giaSP * newSL;
                cthd.setGia(tong_gia);

                // Cập nhật số lượng và tổng giá trong cơ sở dữ liệu
                cthdDAO.changeSL(newSL, tong_gia, idCthd);

                // Cập nhật tổng tiền hóa đơn
                List<hoadon> lstHDByTongtien = hdDAO.getHDByID(idHD);
                for (hoadon hoadons : lstHDByTongtien) {
                    txtTongTien_HD.setText(String.valueOf(hoadons.getTongtien()));
                }

                fillDataTableSanPham();
                // Cập nhật dữ liệu chi tiết hóa đơn trong bảng
                fillDataTableChiTietHoaDon(idHD);

                // Cập nhật giao diện và tìm kiếm voucher
                update();
                searchVoucher();
            } else {
                // Nếu số lượng mới vượt quá số lượng hiện có
                MsgBox.alert(this, "Số lượng sản phẩm đã vượt qua số lượng hiện có trong kho");
                txtSoLuong_ChiTietHoaDon.setValue(slSP);
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ao;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnSua_HD;
    private javax.swing.JButton btnTao_HD;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnXuatHD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbColor;
    private javax.swing.JComboBox<String> cbbDanhMuc;
    private javax.swing.JComboBox<String> cbbSize;
    private javax.swing.JComboBox<String> cbbTH;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JScrollPane jScrollPane10;
    public static javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton jrDaThanhToan;
    private javax.swing.JRadioButton jrDonCho;
    private javax.swing.JLabel lblGhiChu_HD;
    private javax.swing.JLabel lblMa_HD;
    private javax.swing.JLabel lblNgayLap;
    private javax.swing.JLabel lblNgayLap1;
    private javax.swing.JLabel lblNgayLap2;
    public static javax.swing.JLabel lblSoLuong_CTPM2;
    public static javax.swing.JLabel lblSoLuong_CTPM4;
    public static javax.swing.JLabel lblSoLuong_CTPM5;
    public static javax.swing.JLabel lblSoLuong_CTPM6;
    public static javax.swing.JLabel lblSoLuong_CTPM7;
    public static javax.swing.JLabel lblSoLuong_CTPM8;
    private javax.swing.JLabel lblTT_thanhtoan;
    private javax.swing.JLabel lblTbVoucher;
    private javax.swing.JLabel lblTongTien_HD;
    private javax.swing.JLabel lblTongTien_HD1;
    private javax.swing.JLabel lblTrangThai_HD;
    private javax.swing.JLabel lblVoucher;
    private javax.swing.JTextArea taeGhiChu_HD;
    public static javax.swing.JTable tblCTHoaDon_ChiTietHoaDon;
    private javax.swing.JTable tblCTSP;
    public static javax.swing.JTable tblHoaDon_HoaDon;
    private javax.swing.JTextField txtFindProduct;
    private javax.swing.JTextField txtIIDCTHD;
    private javax.swing.JTextField txtMa_HD;
    private javax.swing.JTextField txtNgayLap;
    public static javax.swing.JLabel txtRowHD;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JSpinner txtSoLuong_ChiTietHoaDon;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTongTien_HD;
    private javax.swing.JTextField txtVoucher;
    // End of variables declaration//GEN-END:variables

    hoadon getFormData() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String ngayLap = dateNow.format(formatter);
        hoadon hd = new hoadon();
        hd.setIdnv(Auth.user.getId());
        hd.setSdt(txtSDT.getText());
        hd.setTenkh(txtTenKH.getText());
        hd.setMavocher(txtVoucher.getText());
        hd.setThoigian(ngayLap);
        hd.setGhichu(taeGhiChu_HD.getText());
        hd.setTongtien(Integer.parseInt(txtTongTien_HD.getText()));
        return hd;
    }

    void findByCategory() {
        String name = cbbDanhMuc.getSelectedItem().toString();
        List<ProductDetail> lstPrd = hdDAO.findByCategory(name);
        FillByFindProduct(lstPrd);

    }

    void findByColor() {
        String name = cbbColor.getSelectedItem().toString();
        List<ProductDetail> lstPrd = hdDAO.findByColorProduct(name);
        FillByFindProduct(lstPrd);

    }

    void findByBrand() {
        String name = cbbTH.getSelectedItem().toString();
        List<ProductDetail> lstPrd = hdDAO.findByBrandProduct(name);
        FillByFindProduct(lstPrd);

    }

    void findBySize() {
        String name = cbbSize.getSelectedItem().toString();
        List<ProductDetail> lstPrd = hdDAO.findBySizeProduct(name);
        FillByFindProduct(lstPrd);

    }

    void FillByFindProduct(List<ProductDetail> lstprd) {

        model = (DefaultTableModel) tblCTSP.getModel();
        model.setRowCount(0);
        for (ProductDetail sp : lstprd) {
            Object[] rowData = new Object[9];
            rowData[0] = sp.getProductID();
            rowData[1] = sp.getProductName();
            rowData[2] = sp.getQuantity();
            rowData[3] = sp.getPrice();
            rowData[4] = sp.getCategoryName();
            rowData[5] = sp.getBrandName();
            rowData[6] = sp.getSizeNames();
            rowData[7] = sp.getColorNames();
            if (sp.isProductStatus() == true) {
                rowData[8] = "còn hàng";
            }
            model.addRow(rowData);
        }
    }

    void fillCbbColor() {
        List<mausac> colors = msDao.getAll();
        for (mausac object : colors) {
            cbbColor.addItem(object.getMacsac());
        }
    }

    void fillCbbSize() {
        List<size> lstSize = sizeDao.getAll();
        for (size object : lstSize) {
            cbbSize.addItem(object.getTen());
        }
    }

    void fillCbbTH() {
        List<thuonghieu> lstTH = thDao.getAll();
        for (thuonghieu object : lstTH) {
            cbbTH.addItem(object.getTen());
        }
    }

    void fillCbbDM() {
        List<danhmuc> lstdanhmuc = dmDao.getAll();
        for (danhmuc object : lstdanhmuc) {
            cbbDanhMuc.addItem(object.getTen());
        }
    }

    void fillDataTableSanPham() {
        model = (DefaultTableModel) tblCTSP.getModel();
        List<ProductDetail> prdDetail = hdDAO.fillAllProduct();
        model.setRowCount(0);
        for (ProductDetail sp : prdDetail) {
            Object[] rowData = new Object[9];
            rowData[0] = sp.getProductID();
            rowData[1] = sp.getProductName();
            rowData[2] = sp.getQuantity();
            rowData[3] = sp.getPrice();
            rowData[4] = sp.getCategoryName();
            rowData[5] = sp.getBrandName();
            rowData[6] = sp.getSizeNames();
            rowData[7] = sp.getColorNames();
            if (sp.isProductStatus() == true) {
                rowData[8] = "còn hàng";
            }
            model.addRow(rowData);
        }

    }

    void fillDataTableHoaDon(List<hoadon> lhd) {
        model = (DefaultTableModel) tblHoaDon_HoaDon.getModel();
        model.setRowCount(0);
        for (hoadon hd : lhd) {
            Object[] rowData = new Object[10];
            rowData[0] = hd.getId();
            rowData[1] = hd.getIdnv();
            rowData[2] = hd.getSdt();
            rowData[3] = hd.getTenkh();
            rowData[4] = hd.getMavocher();
            rowData[5] = hd.getThoigian();
            rowData[6] = hd.getTongtien();
            rowData[7] = hd.getTtthanhtoan();
            rowData[8] = hd.getGhichu();
            rowData[9] = hd.getTrangthai();
            model.addRow(rowData);
        }
    }

    void fillDataTableChiTietHoaDon(int id) {
        model = (DefaultTableModel) tblCTHoaDon_ChiTietHoaDon.getModel();
        model.setRowCount(0);

        for (chitiethoadon cthd : cthdDAO.findByIDHD(id)) {
            Object[] rowData = new Object[7];
            rowData[0] = cthd.getId();
            rowData[1] = cthd.getIdctsp();
            rowData[2] = cthd.getTenSP();
            rowData[3] = cthd.getSoluong();
            rowData[4] = cthd.getDon_gia();
            rowData[5] = cthd.getGia();
            rowData[6] = cthd.isTrangthai();
            model.addRow(rowData);
        }
    }

    void ngayTaoHD() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String ngayLap = dateNow.format(formatter);
        txtNgayLap.setText(ngayLap);
    }
}
