/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import DAO.chiTietHoaDonDAO;
import DAO.chitietsanphamDAO;
import DAO.danhMucDAO;
import DAO.hoaDonDAO;
import DAO.mauSacDAO;
import DAO.nhanhVienDAO;
import DAO.sanPhamDAO;
import DAO.sizeDAO;
import DAO.thuongHieuDAO;
import DAO.voucherDAO;
import Helper.Auth;
import View.viewModel.ProductDetail;
import entity.chitiethoadon;
import entity.danhmuc;
import entity.hoadon;
import entity.mausac;
import entity.sanpham;
import entity.size;
import entity.thuonghieu;
import entity.voucher;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huyen
 */
public class quanLyBanHangs extends javax.swing.JPanel {

    LocalDate currentDate = LocalDate.now();
    LocalDateTime dateNow = LocalDateTime.now();
    private voucherDAO vcDao;
    private sizeDAO sizeDao;
    private mauSacDAO msDao;
    private danhMucDAO dmDao;
    private thuongHieuDAO thDao;
    private sanPhamDAO spDAO;
    private hoaDonDAO hdDAO;
    private nhanhVienDAO nvDAO;
    private chiTietHoaDonDAO cthdDAO;
    private chitietsanphamDAO ctspDao;
    DefaultTableModel model;

    /**
     * Creates new form quanLyBanHang
     */
    public quanLyBanHangs() {
        initComponents();
        ctspDao = new chitietsanphamDAO();
        vcDao = new voucherDAO();
        msDao = new mauSacDAO();
        hdDAO = new hoaDonDAO();
        dmDao = new danhMucDAO();
        thDao = new thuongHieuDAO();
        sizeDao = new sizeDAO();
        cthdDAO = new chiTietHoaDonDAO() {
            @Override
            public List<chitiethoadon> findByID(int id) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        };
        ngayTaoHD();

        fillDataTableHoaDon();
        fillCbbSize();
        fillCbbTH();
        fillCbbDM();
        fillCbbColor();
        fillDataTableSanPham();
//        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTSP = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblHoaDon_HoaDon = new javax.swing.JTable();
        txtFindProduct = new javax.swing.JTextField();
        lblSoLuong_CTPM2 = new javax.swing.JLabel();
        lblSoLuong_CTPM3 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblCTHoaDon_ChiTietHoaDon = new javax.swing.JTable();
        lblSoLuong_CTPM4 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtSoLuong_ChiTietHoaDon = new javax.swing.JSpinner();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cbbSize = new javax.swing.JComboBox<>();
        cbbTH = new javax.swing.JComboBox<>();
        cbbDanhMuc = new javax.swing.JComboBox<>();
        lblSoLuong_CTPM5 = new javax.swing.JLabel();
        lblSoLuong_CTPM6 = new javax.swing.JLabel();
        lblSoLuong_CTPM7 = new javax.swing.JLabel();
        cbbColor = new javax.swing.JComboBox<>();
        lblSoLuong_CTPM8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMa_HD = new javax.swing.JLabel();
        txtMa_HD = new javax.swing.JTextField();
        lblNgayLap = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taeGhiChu_HD = new javax.swing.JTextArea();
        lblGhiChu_HD = new javax.swing.JLabel();
        lblTongTien_HD = new javax.swing.JLabel();
        txtTongTien_HD = new javax.swing.JTextField();
        lblTrangThai_HD = new javax.swing.JLabel();
        jrDonCho = new javax.swing.JRadioButton();
        jrDaThanhToan = new javax.swing.JRadioButton();
        btnTao_HD = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnSua_HD = new javax.swing.JButton();
        lblVoucher = new javax.swing.JLabel();
        txtVoucher = new javax.swing.JTextField();
        lblTbVoucher = new javax.swing.JLabel();
        lblTT_thanhtoan = new javax.swing.JLabel();
        lblTongTien_HD1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(1065, 498));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản phẩm"));

        tblCTSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên sản phẩm", "Số lượng", "Đơn Giá", "Danh mục", "Thương hiệu", "Kích cỡ", "Màu", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCTSP.setRowHeight(30);
        tblCTSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTSPMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblCTSPMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblCTSP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Hoá đơn"));

        tblHoaDon_HoaDon.setAutoCreateRowSorter(true);
        tblHoaDon_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Nhân Viên", "Voucher ", "Ngày lập hoá đơn", "Tổng tiền", "Ghi chú", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblHoaDon_HoaDon.setPreferredSize(new java.awt.Dimension(825, 220));
        tblHoaDon_HoaDon.setRowHeight(30);
        tblHoaDon_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblHoaDon_HoaDonMouseReleased(evt);
            }
        });
        jScrollPane10.setViewportView(tblHoaDon_HoaDon);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        txtFindProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindProductActionPerformed(evt);
            }
        });
        txtFindProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindProductKeyReleased(evt);
            }
        });

        lblSoLuong_CTPM2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM2.setText("Tìm Kiếm");
        lblSoLuong_CTPM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM2MouseClicked(evt);
            }
        });

        lblSoLuong_CTPM3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM3.setText("Tìm Kiếm");
        lblSoLuong_CTPM3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM3MouseClicked(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi Tiết Hoá Đơn"));

        tblCTHoaDon_ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Giá", "Trạng thái"
            }
        ));
        tblCTHoaDon_ChiTietHoaDon.setRowHeight(30);
        tblCTHoaDon_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTHoaDon_ChiTietHoaDonMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblCTHoaDon_ChiTietHoaDonMouseReleased(evt);
            }
        });
        jScrollPane15.setViewportView(tblCTHoaDon_ChiTietHoaDon);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        lblSoLuong_CTPM4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM4.setText("Tìm Kiếm");
        lblSoLuong_CTPM4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM4MouseClicked(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Số lượng");

        txtSoLuong_ChiTietHoaDon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtSoLuong_ChiTietHoaDonStateChanged(evt);
            }
        });
        txtSoLuong_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSoLuong_ChiTietHoaDonMouseClicked(evt);
            }
        });
        txtSoLuong_ChiTietHoaDon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSoLuong_ChiTietHoaDonPropertyChange(evt);
            }
        });

        jButton4.setText("Thêm");

        jButton5.setText("Xoá");

        cbbSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSizeActionPerformed(evt);
            }
        });

        cbbTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTHActionPerformed(evt);
            }
        });

        cbbDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbDanhMucActionPerformed(evt);
            }
        });

        lblSoLuong_CTPM5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM5.setText("Size");
        lblSoLuong_CTPM5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM5MouseClicked(evt);
            }
        });

        lblSoLuong_CTPM6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM6.setText("Thương hiệu");
        lblSoLuong_CTPM6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM6MouseClicked(evt);
            }
        });

        lblSoLuong_CTPM7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM7.setText("Danh mục");
        lblSoLuong_CTPM7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM7MouseClicked(evt);
            }
        });

        cbbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL" }));
        cbbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbColorActionPerformed(evt);
            }
        });

        lblSoLuong_CTPM8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSoLuong_CTPM8.setText("Màu");
        lblSoLuong_CTPM8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoLuong_CTPM8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblSoLuong_CTPM4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSoLuong_CTPM3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoLuong_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblSoLuong_CTPM2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoLuong_CTPM8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoLuong_CTPM5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSoLuong_CTPM6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbTH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoLuong_CTPM7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSoLuong_CTPM8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSoLuong_CTPM2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFindProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong_CTPM5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong_CTPM6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSoLuong_CTPM7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoLuong_CTPM4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuong_CTPM3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtSoLuong_ChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hoá Đơn"));

        lblMa_HD.setText("Mã Hoá Đơn");

        txtMa_HD.setEditable(false);

        lblNgayLap.setText("Ngày lập");

        txtNgayLap.setEditable(false);

        taeGhiChu_HD.setColumns(20);
        taeGhiChu_HD.setRows(5);
        jScrollPane3.setViewportView(taeGhiChu_HD);

        lblGhiChu_HD.setText("Ghi chú");

        lblTongTien_HD.setText("Tổng tiền");

        txtTongTien_HD.setEditable(false);
        txtTongTien_HD.setText("0");

        lblTrangThai_HD.setText("Trạng thái");

        buttonGroup1.add(jrDonCho);
        jrDonCho.setText("Đơn chờ");
        jrDonCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDonChoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrDaThanhToan);
        jrDaThanhToan.setText("Đã thanh toán");
        jrDaThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDaThanhToanActionPerformed(evt);
            }
        });

        btnTao_HD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTao_HD.setText("Tạo hoá đơn");
        btnTao_HD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTao_HDActionPerformed(evt);
            }
        });

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThanhToan.setText("Thanh toán");

        btnSua_HD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua_HD.setText("Sửa");

        lblVoucher.setText("Voucher ");

        txtVoucher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVoucherKeyReleased(evt);
            }
        });

        lblTbVoucher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTbVoucher.setText("Voucher ");

        lblTT_thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTT_thanhtoan.setText("Thanh Toan");

        lblTongTien_HD1.setText("Cần thanh toán");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGhiChu_HD)
                            .addComponent(lblMa_HD)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTongTien_HD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTongTien_HD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblNgayLap)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVoucher)
                                    .addComponent(lblTrangThai_HD))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrDonCho, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTT_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtTongTien_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMa_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTbVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnTao_HD, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addComponent(btnSua_HD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReset)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMa_HD)
                    .addComponent(txtMa_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayLap)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien_HD)
                    .addComponent(txtTongTien_HD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien_HD1)
                    .addComponent(lblTT_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoucher)
                    .addComponent(txtVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblTbVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrangThai_HD)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrDonCho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrDaThanhToan)))
                        .addGap(28, 28, 28)
                        .addComponent(btnTao_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSua_HD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGhiChu_HD))
                .addGap(26, 26, 26)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCTSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseClicked

    }//GEN-LAST:event_tblCTSPMouseClicked

    private void tblCTSPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseReleased
        int row = tblCTSP.getSelectedRow();
        int idCTSP = Integer.parseInt(tblCTSP.getValueAt(row, 0).toString());
        double giaSP = Double.parseDouble(tblCTSP.getValueAt(row, 3).toString());

        ProductDetail prd = hdDAO.fillSLvsGiaProduct(idCTSP);

        List<chitiethoadon> lstCTHD = cthdDAO.selectSLByIDCTSP(Integer.valueOf(txtMa_HD.getText()), idCTSP);
        if (prd != null) {
            if (lstCTHD.isEmpty()) {
                chitiethoadon op = new chitiethoadon();
                op.setIdhd(Integer.valueOf(txtMa_HD.getText()));
                op.setIdctsp(idCTSP);
                op.setTenSP(prd.getProductName());
                op.setSoluong(1);
                op.setGia(prd.getPrice());
                cthdDAO.add(op);
                fillDataTableChiTietHoaDon(Integer.valueOf(txtMa_HD.getText()));
            }else {
                chitiethoadon ctV2 = lstCTHD.get(0);
                int tangSL = ctV2.getSoluong() + 1;
                ctV2.setSoluong(tangSL);
                double gia = prd.getPrice();
                double tong_gia = gia * tangSL;
                ctV2.setGia(tong_gia);
                cthdDAO.updateSL(ctV2);
            }
        }
        fillDataTableChiTietHoaDon(Integer.valueOf(txtMa_HD.getText()));
        fillDataTableHoaDon();
    }//GEN-LAST:event_tblCTSPMouseReleased

    private void tblHoaDon_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMouseClicked
        //        System.out.println("clicked");
    }//GEN-LAST:event_tblHoaDon_HoaDonMouseClicked

    private void tblHoaDon_HoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDon_HoaDonMouseEntered

    private void tblHoaDon_HoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDon_HoaDonMousePressed

    private void tblHoaDon_HoaDonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDon_HoaDonMouseReleased
        int row = tblHoaDon_HoaDon.getSelectedRow();
        txtMa_HD.setText(tblHoaDon_HoaDon.getValueAt(row, 0).toString());
        txtVoucher.setText(tblHoaDon_HoaDon.getValueAt(row, 2).toString());
        txtNgayLap.setText(tblHoaDon_HoaDon.getValueAt(row, 3).toString());
        txtTongTien_HD.setText(tblHoaDon_HoaDon.getValueAt(row, 4).toString());
        taeGhiChu_HD.setText(tblHoaDon_HoaDon.getValueAt(row, 5).toString());
        String trangThai = tblHoaDon_HoaDon.getValueAt(row, 6).toString();
        if (trangThai.equals("true")) {
            jrDonCho.setSelected(true);
        } else {
            jrDaThanhToan.setSelected(true);
        }
        int id = Integer.valueOf(txtMa_HD.getText());
        fillDataTableChiTietHoaDon(id);
    }//GEN-LAST:event_tblHoaDon_HoaDonMouseReleased

    private void txtFindProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindProductActionPerformed

    private void lblSoLuong_CTPM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM2MouseClicked

    private void lblSoLuong_CTPM3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM3MouseClicked

    private void tblCTHoaDon_ChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHoaDon_ChiTietHoaDonMouseClicked

    }//GEN-LAST:event_tblCTHoaDon_ChiTietHoaDonMouseClicked

    private void tblCTHoaDon_ChiTietHoaDonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTHoaDon_ChiTietHoaDonMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tblCTHoaDon_ChiTietHoaDonMouseReleased

    private void txtSoLuong_ChiTietHoaDonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtSoLuong_ChiTietHoaDonStateChanged

    }//GEN-LAST:event_txtSoLuong_ChiTietHoaDonStateChanged

    private void txtSoLuong_ChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSoLuong_ChiTietHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuong_ChiTietHoaDonMouseClicked

    private void txtSoLuong_ChiTietHoaDonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSoLuong_ChiTietHoaDonPropertyChange

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuong_ChiTietHoaDonPropertyChange

    private void lblSoLuong_CTPM4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM4MouseClicked

    private void jrDonChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDonChoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrDonChoActionPerformed

    private void jrDaThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDaThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrDaThanhToanActionPerformed

    private void txtFindProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindProductKeyReleased
        // TODO add your handling code here:
//        System.out.println(jTextField9.getText());
        String name = txtFindProduct.getText();
        List<ProductDetail> lstprd = hdDAO.findByNameProduct(name);
        FillByFindProduct(lstprd);
    }//GEN-LAST:event_txtFindProductKeyReleased

    private void lblSoLuong_CTPM5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM5MouseClicked

    private void lblSoLuong_CTPM6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM6MouseClicked

    private void lblSoLuong_CTPM7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM7MouseClicked

    private void cbbDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDanhMucActionPerformed
        // TODO add your handling code here:
        findByCategory();
    }//GEN-LAST:event_cbbDanhMucActionPerformed

    private void lblSoLuong_CTPM8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoLuong_CTPM8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoLuong_CTPM8MouseClicked

    private void cbbSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSizeActionPerformed
        // TODO add your handling code here:
        findBySize();
    }//GEN-LAST:event_cbbSizeActionPerformed

    private void cbbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbColorActionPerformed
        // TODO add your handling code here:
        if (cbbColor.getSelectedItem().equals("ALL")) {
            fillDataTableSanPham();
        } else {

            findByColor();
        }
    }//GEN-LAST:event_cbbColorActionPerformed

    private void cbbTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTHActionPerformed
        // TODO add your handling code here:
        findByBrand();
    }//GEN-LAST:event_cbbTHActionPerformed

    private void btnTao_HDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTao_HDActionPerformed
        // TODO add your handling code here:
        txtTongTien_HD.setText("0");
        hdDAO.add(getFormData());
        fillDataTableHoaDon();
    }//GEN-LAST:event_btnTao_HDActionPerformed

    private void txtVoucherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoucherKeyReleased
        // TODO add your handling code here:
        voucher vouchers = vcDao.findByID(txtVoucher.getText());
        if (txtVoucher.getText().trim().isEmpty()) {
            lblTbVoucher.setText("");
            btnTao_HD.setEnabled(true);
            return;
        }

        if (vouchers == null) {
            lblTbVoucher.setForeground(Color.red);
            lblTbVoucher.setText("voucher không tồn tại");
            System.out.println("voucher không tồn tại");
            btnTao_HD.setEnabled(false);
        } else {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String stopDate = vouchers.getNgayketthuc();
            LocalDate inputDate = LocalDate.parse(stopDate, formatter);
            if (currentDate.isAfter(inputDate)) {

                lblTbVoucher.setForeground(Color.red);
                lblTbVoucher.setText("voucher đã hết hạn");
                System.out.println(vouchers.getNgayketthuc());
                btnTao_HD.setEnabled(false);

            } else if (currentDate.isBefore(inputDate)) {

                lblTbVoucher.setForeground(Color.green);
                lblTbVoucher.setText("voucher có hiệu lực");
                System.out.println(vouchers.getNgayketthuc());
                btnTao_HD.setEnabled(true);
            } else {

                lblTbVoucher.setForeground(Color.green);
                lblTbVoucher.setText("voucher có hiệu lực");
                System.out.println(vouchers.getNgayketthuc());
                btnTao_HD.setEnabled(true);
            }
        }
    }//GEN-LAST:event_txtVoucherKeyReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtFindProduct.setText("");
        txtMa_HD.setText("");
        txtNgayLap.setText("");
        txtSoLuong_ChiTietHoaDon.setValue(0);
        txtTongTien_HD.setText("");
        txtVoucher.setText("");
        taeGhiChu_HD.setText("");
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua_HD;
    private javax.swing.JButton btnTao_HD;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbColor;
    private javax.swing.JComboBox<String> cbbDanhMuc;
    private javax.swing.JComboBox<String> cbbSize;
    private javax.swing.JComboBox<String> cbbTH;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    public static javax.swing.JScrollPane jScrollPane10;
    public static javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JRadioButton jrDaThanhToan;
    private javax.swing.JRadioButton jrDonCho;
    private javax.swing.JLabel lblGhiChu_HD;
    private javax.swing.JLabel lblMa_HD;
    private javax.swing.JLabel lblNgayLap;
    public static javax.swing.JLabel lblSoLuong_CTPM2;
    public static javax.swing.JLabel lblSoLuong_CTPM3;
    public static javax.swing.JLabel lblSoLuong_CTPM4;
    public static javax.swing.JLabel lblSoLuong_CTPM5;
    public static javax.swing.JLabel lblSoLuong_CTPM6;
    public static javax.swing.JLabel lblSoLuong_CTPM7;
    public static javax.swing.JLabel lblSoLuong_CTPM8;
    private javax.swing.JLabel lblTT_thanhtoan;
    private javax.swing.JLabel lblTbVoucher;
    private javax.swing.JLabel lblTongTien_HD;
    private javax.swing.JLabel lblTongTien_HD1;
    private javax.swing.JLabel lblTrangThai_HD;
    private javax.swing.JLabel lblVoucher;
    private javax.swing.JTextArea taeGhiChu_HD;
    public static javax.swing.JTable tblCTHoaDon_ChiTietHoaDon;
    private javax.swing.JTable tblCTSP;
    public static javax.swing.JTable tblHoaDon_HoaDon;
    private javax.swing.JTextField txtFindProduct;
    private javax.swing.JTextField txtMa_HD;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JSpinner txtSoLuong_ChiTietHoaDon;
    private javax.swing.JTextField txtTongTien_HD;
    private javax.swing.JTextField txtVoucher;
    // End of variables declaration//GEN-END:variables

    hoadon getFormData() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String ngayLap = dateNow.format(formatter);
        hoadon hd = new hoadon();
        hd.setIdnv(Auth.user.getId());
        hd.setMavocher(txtVoucher.getText());
        hd.setThoigian(ngayLap);
        hd.setGhichu(taeGhiChu_HD.getText());
        hd.setTongtien(Integer.parseInt(txtTongTien_HD.getText()));
        return hd;
    }

    void findByCategory() {
        String name = cbbDanhMuc.getSelectedItem().toString();
        List<ProductDetail> lstPrd = hdDAO.findByCategory(name);
        FillByFindProduct(lstPrd);

    }

    void findByColor() {
        String name = cbbColor.getSelectedItem().toString();
        List<ProductDetail> lstPrd = hdDAO.findByColorProduct(name);
        FillByFindProduct(lstPrd);

    }

    void findByBrand() {
        String name = cbbTH.getSelectedItem().toString();
        List<ProductDetail> lstPrd = hdDAO.findByBrandProduct(name);
        FillByFindProduct(lstPrd);

    }

    void findBySize() {
        String name = cbbSize.getSelectedItem().toString();
        List<ProductDetail> lstPrd = hdDAO.findBySizeProduct(name);
        FillByFindProduct(lstPrd);

    }

    void FillByFindProduct(List<ProductDetail> lstprd) {

        model = (DefaultTableModel) tblCTSP.getModel();
        model.setRowCount(0);
        for (ProductDetail sp : lstprd) {
            Object[] rowData = new Object[9];
            rowData[0] = sp.getProductID();
            rowData[1] = sp.getProductName();
            rowData[2] = sp.getQuantity();
            rowData[3] = sp.getPrice();
            rowData[4] = sp.getCategoryName();
            rowData[5] = sp.getBrandName();
            rowData[6] = sp.getSizeNames();
            rowData[7] = sp.getColorNames();
            if (sp.isProductStatus() == true) {
                rowData[8] = "còn hàng";
            }
            model.addRow(rowData);
        }
    }

    void fillCbbColor() {
        List<mausac> colors = msDao.getAll();
        for (mausac object : colors) {
            cbbColor.addItem(object.getMacsac());
        }
    }

    void fillCbbSize() {
        List<size> lstSize = sizeDao.getAll();
        for (size object : lstSize) {
            cbbSize.addItem(object.getTen());
        }
    }

    void fillCbbTH() {
        List<thuonghieu> lstTH = thDao.getAll();
        for (thuonghieu object : lstTH) {
            cbbTH.addItem(object.getTen());
        }
    }

    void fillCbbDM() {
        List<danhmuc> lstdanhmuc = dmDao.getAll();
        for (danhmuc object : lstdanhmuc) {
            cbbDanhMuc.addItem(object.getTen());
        }
    }

    void fillDataTableSanPham() {
        model = (DefaultTableModel) tblCTSP.getModel();
        List<ProductDetail> prdDetail = hdDAO.fillAllProduct();
        model.setRowCount(0);
        for (ProductDetail sp : prdDetail) {
            Object[] rowData = new Object[9];
            rowData[0] = sp.getProductID();
            rowData[1] = sp.getProductName();
            rowData[2] = sp.getQuantity();
            rowData[3] = sp.getPrice();
            rowData[4] = sp.getCategoryName();
            rowData[5] = sp.getBrandName();
            rowData[6] = sp.getSizeNames();
            rowData[7] = sp.getColorNames();
            if (sp.isProductStatus() == true) {
                rowData[8] = "còn hàng";
            }
            model.addRow(rowData);
        }

    }

    void fillDataTableHoaDon() {
        model = (DefaultTableModel) tblHoaDon_HoaDon.getModel();
        model.setRowCount(0);
        List<hoadon> lhd = hdDAO.getAll();
        for (hoadon hd : lhd) {
            Object[] rowData = new Object[7];
            rowData[0] = hd.getId();
            rowData[1] = hd.getIdnv();
            rowData[2] = hd.getMavocher();
            rowData[3] = hd.getThoigian();
            rowData[4] = hd.getTongtien();
            rowData[5] = hd.getGhichu();
            rowData[6] = hd.isTrangthai();
            model.addRow(rowData);
        }
    }

    void fillDataTableChiTietHoaDon(int id) {
        model = (DefaultTableModel) tblCTHoaDon_ChiTietHoaDon.getModel();
        model.setRowCount(0);

        for (chitiethoadon cthd : cthdDAO.findByIDHD(id)) {
            Object[] rowData = new Object[6];
            rowData[0] = cthd.getId();
            rowData[1] = cthd.getIdctsp();
            rowData[2] = cthd.getTenSP();
            rowData[3] = cthd.getSoluong();
            rowData[4] = cthd.getGia();
            rowData[5] = cthd.isTrangthai();
            model.addRow(rowData);
        }
    }

    void ngayTaoHD() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String ngayLap = dateNow.format(formatter);
        txtNgayLap.setText(ngayLap);
    }
}
