/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;
import java.util.*;
import DAO.chiTietHoaDonDAO;
import DAO.mauSacDAO;
import DAO.danhMucDAO;
import DAO.thuongHieuDAO;
import DAO.sizeDAO;
import DAO.thongkeDAO;

import entity.chitiethoadon;
import entity.mausac;
import entity.danhmuc;
import entity.thuonghieu;
import entity.size;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author letnp
 */
public class ThongKe1 extends javax.swing.JDialog {

    /**
     * Creates new form ThongKe1
     */
    DefaultTableModel model;
    List<chitiethoadon> cthoadons;
    List<danhmuc> danhmucs;
    List<thuonghieu> thuonghieus;
    List<mausac> mausacs;
    List<size> sizes;
    List<Object[]> sanphams;
    public ThongKe1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sanphams = new ArrayList<>();
        resetComboBox();
        resetTable();
    }
    void resetComboBox(){
        cbbYear.removeAllItems();
        cbbMonth.removeAllItems();
        getYear();
        cbbParent.removeAllItems();
        cbbParent.addItem("Danh mục");
        cbbParent.addItem("Thương hiệu");
        cbbParent.setSelectedIndex(0);
        getDanhMuc();
        sanphams = new thongkeDAO().getAllSP_DM(Integer.parseInt(cbbMonth.getSelectedItem().toString()),Integer.parseInt(cbbYear.getSelectedItem().toString()));
    }
    void resetTable(){
        model = new DefaultTableModel();
        model. addColumn("ID");
        model. addColumn("Tên sản phẩm");
        model. addColumn("Giá");
        model. addColumn("Số lượng đã bán");
        model. addColumn("Doanh thu");
        model. addColumn(cbbParent.getSelectedItem());
        for( Object[] x :sanphams){
            model.addRow(x);
        }
        tblThongKe.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cbbParent = new javax.swing.JComboBox<>();
        cbbChild = new javax.swing.JComboBox<>();
        cbbYear = new javax.swing.JComboBox<>();
        cbbMonth = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("FILTER"));

        cbbParent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbParentActionPerformed(evt);
            }
        });

        cbbChild.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChildActionPerformed(evt);
            }
        });

        cbbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbYearActionPerformed(evt);
            }
        });

        cbbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMonthActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setText("Xuất PDF");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbParent, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbChild, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(cbbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblThongKe);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane4.addTab("SẢN PHẨM", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("DOANH THU", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void getYear(){
        List<Integer> years = new thongkeDAO().getYearFromHD();
        for(Integer x : years){
            System.out.println(x);
            cbbYear.addItem(x.toString());
        }
        cbbYear.setSelectedIndex(0);
        getMonth(Integer.parseInt(cbbYear.getSelectedItem().toString()));
    }
    void getMonth(int year){
        cbbMonth.removeAllItems();
        List<Integer> months = new thongkeDAO().getMonthFromHD(year);
        for(Integer x : months){
            cbbMonth.addItem(x.toString());
        }
        cbbMonth.setSelectedIndex(0);
    }
    void getDanhMuc(){
        danhmucs = new danhMucDAO().getAll();
        cbbChild.removeAllItems();
        cbbChild.addItem("Tất cả");
        for(danhmuc x: danhmucs){
            cbbChild.addItem(x.getTen());
        }
    }
    void getThuongHieu(){
        thuonghieus = new thuongHieuDAO().getAll();
        cbbChild.removeAllItems();
        cbbChild.addItem("Tất cả");
        for(thuonghieu x: thuonghieus){
            cbbChild.addItem(x.getTen());
        }
    }
//    void get_Size(){
//        sizes = new sizeDAO().getAll();
//        cbbChild.removeAllItems();
//        cbbChild.addItem("Tất cả");
//        for(size x: sizes){
//            cbbChild.addItem(x.getTen());
//        }
//    }
//    void getMauSac(){
//        mausacs = new mauSacDAO().getAll();
//        cbbChild.removeAllItems();
//        cbbChild.addItem("Tất cả");
//        for(mausac x: mausacs){
//            cbbChild.addItem(x.getMacsac());
//        }
//    }

    void getSanPham(){
        int choice = cbbParent.getSelectedIndex();
        int id = cbbChild.getSelectedIndex();
        int year = 0;
        int month =0;
        try{
            year = Integer.parseInt(cbbYear.getSelectedItem().toString());
            month =Integer.parseInt(cbbMonth.getSelectedItem().toString());
          
        }catch(Exception e){
            System.out.println("hhjhj");
        }
        
        switch (choice){
            case 0: 
                sanphams = id ==0 ? new thongkeDAO().getAllSP_DM(month, year):new thongkeDAO().getSP_DM(id, month, year);
                resetTable();
                break;
            case 1:
                sanphams = id ==0 ? new thongkeDAO().getAllSP_TH(month, year):new thongkeDAO().getSP_TH(id, month, year);
                resetTable();
                break;
            default:
                cbbChild.removeAllItems();
                cbbChild.addItem("Tất cả");
        }
        resetTable();
    }
    private void cbbParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbParentActionPerformed
        // TODO add your handling code here:
        int choice = cbbParent.getSelectedIndex();
        switch (choice){
            case 0:
                getDanhMuc();
                break;
            case 1:
                getThuongHieu();
                break;
            default:
                cbbChild.removeAllItems();
                cbbChild.addItem("Tất cả");
        }
        getSanPham();
        resetTable();
    }//GEN-LAST:event_cbbParentActionPerformed

    private void cbbChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChildActionPerformed
        // TODO add your handling code here:
        getSanPham();
        resetTable();
    }//GEN-LAST:event_cbbChildActionPerformed

    private void cbbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbYearActionPerformed
        // TODO add your handling code here:
//        int year = Integer.parseInt(cbbYear.getSelectedItem().toString());
        int year = cbbYear.getSelectedItem() == null ? 2023 : Integer.parseInt(cbbYear.getSelectedItem().toString());
        getMonth(year);
        getSanPham();
        resetTable();
//        System.out.println("hiii");
    }//GEN-LAST:event_cbbYearActionPerformed

    private void cbbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMonthActionPerformed
        // TODO add your handling code here:
        getSanPham();
        resetTable();
    }//GEN-LAST:event_cbbMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThongKe1 dialog = new ThongKe1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbChild;
    private javax.swing.JComboBox<String> cbbMonth;
    private javax.swing.JComboBox<String> cbbParent;
    private javax.swing.JComboBox<String> cbbYear;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables
}
